# app/gics.py
# S&P500 목록(GICS 업종 분류)은 영문으로만 옵니다. 화면 전체가 한글이라
# 회사 개요만 영문으로 나오면 어색해서, 자주 나오는 값 위주로 번역해 둡니다.
# 목록에 없는 값은 영문 그대로 씁니다 (틀리게 옮기는 것보다 낫습니다).

SECTOR_KO = {
    "Communication Services": "커뮤니케이션 서비스",
    "Consumer Discretionary": "임의소비재",
    "Consumer Staples": "필수소비재",
    "Energy": "에너지",
    "Financials": "금융",
    "Health Care": "헬스케어",
    "Industrials": "산업재",
    "Information Technology": "정보기술",
    "Materials": "소재",
    "Real Estate": "부동산",
    "Utilities": "유틸리티",
}

SUB_INDUSTRY_KO = {
    "Advertising": "광고",
    "Agricultural Products & Services": "농산물 및 서비스",
    "Air Freight & Logistics": "항공화물 및 물류",
    "Apparel Retail": "의류 소매",
    "Apparel, Accessories & Luxury Goods": "의류·액세서리 및 명품",
    "Application Software": "응용 소프트웨어",
    "Aerospace & Defense": "항공우주 및 방위",
    "Asset Management & Custody Banks": "자산운용 및 수탁은행",
    "Automotive Parts & Equipment": "자동차 부품 및 장비",
    "Automotive Retail": "자동차 소매",
    "Automobile Manufacturers": "자동차 제조",
    "Beverage Retail": "음료 소매",
    "Biotechnology": "바이오테크놀로지",
    "Brewers": "맥주 제조",
    "Broadline Retail": "종합 소매",
    "Broadcasting": "방송",
    "Building Products": "건축자재",
    "Cable & Satellite": "케이블 및 위성방송",
    "Cargo Ground Transportation": "화물 육상운송",
    "Casinos & Gaming": "카지노 및 게임",
    "Communications Equipment": "통신장비",
    "Computer & Electronics Retail": "컴퓨터·전자제품 소매",
    "Construction & Engineering": "건설 및 엔지니어링",
    "Construction Machinery & Heavy Transportation Equipment": "건설기계 및 중장비",
    "Construction Materials": "건설자재",
    "Consumer Electronics": "가전제품",
    "Consumer Finance": "소비자금융",
    "Consumer Staples Merchandise Retail": "생활필수품 소매",
    "Copper": "구리",
    "Data Center REITs": "데이터센터 리츠",
    "Data Processing & Outsourced Services": "데이터 처리 및 아웃소싱 서비스",
    "Distillers & Vintners": "증류주 및 와인",
    "Diversified Banks": "종합은행",
    "Diversified Support Services": "종합 지원서비스",
    "Distributors": "유통업체",
    "Electronic Components": "전자부품",
    "Electronic Equipment & Instruments": "전자장비 및 계측기",
    "Electronic Manufacturing Services": "전자제품 위탁생산",
    "Environmental & Facilities Services": "환경 및 시설관리 서비스",
    "Fertilizers & Agricultural Chemicals": "비료 및 농업용 화학제품",
    "Financial Exchanges & Data": "금융거래소 및 데이터",
    "Food Distributors": "식품 유통",
    "Food Retail": "식품 소매",
    "Footwear": "신발",
    "Gas Utilities": "가스 유틸리티",
    "Gold": "금",
    "Health Care Distributors": "의료용품 유통",
    "Health Care Equipment": "의료기기",
    "Health Care Facilities": "의료시설",
    "Health Care Services": "의료서비스",
    "Health Care Supplies": "의료소모품",
    "Health Care Technology": "헬스케어 기술",
    "Heavy Electrical Equipment": "중전기기",
    "Homebuilding": "주택건설",
    "Homefurnishing Retail": "가구·인테리어 소매",
    "Household Products": "생활용품",
    "Hotel & Resort REITs": "호텔·리조트 리츠",
    "Hotels, Resorts & Cruise Lines": "호텔·리조트 및 크루즈",
    "Human Resource & Employment Services": "인력·고용 서비스",
    "Independent Power Producers & Energy Traders": "독립발전 및 에너지 트레이딩",
    "Industrial Conglomerates": "산업 복합기업",
    "Industrial Gases": "산업용 가스",
    "Industrial Machinery & Supplies & Components": "산업기계 및 부품",
    "Insurance Brokers": "보험중개",
    "Integrated Oil & Gas": "종합 석유·가스",
    "Integrated Telecommunication Services": "종합 통신서비스",
    "Interactive Home Entertainment": "인터랙티브 홈 엔터테인먼트",
    "Interactive Media & Services": "인터랙티브 미디어 및 서비스",
    "Internet Services & Infrastructure": "인터넷 서비스 및 인프라",
    "Investment Banking & Brokerage": "투자은행 및 증권중개",
    "IT Consulting & Other Services": "IT 컨설팅 및 기타 서비스",
    "Leisure Products": "레저용품",
    "Life & Health Insurance": "생명·건강보험",
    "Life Sciences Tools & Services": "생명과학 도구 및 서비스",
    "Managed Health Care": "관리형 건강보험",
    "Metal, Glass & Plastic Containers": "금속·유리·플라스틱 용기",
    "Movies & Entertainment": "영화 및 엔터테인먼트",
    "Multi-Family Residential REITs": "다세대주택 리츠",
    "Multi-line Insurance": "종합보험",
    "Multi-Utilities": "복합 유틸리티",
    "Pharmaceuticals": "제약",
    "Paper & Plastic Packaging Products & Materials": "종이·플라스틱 포장재",
    "Passenger Airlines": "여객 항공",
    "Passenger Ground Transportation": "여객 육상운송",
    "Personal Care Products": "퍼스널케어 제품",
    "Property & Casualty Insurance": "손해보험",
    "Publishing": "출판",
    "Rail Transportation": "철도운송",
    "Regional Banks": "지역은행",
    "Reinsurance": "재보험",
    "Research & Consulting Services": "리서치 및 컨설팅 서비스",
    "Restaurants": "외식업",
    "Retail REITs": "리테일 리츠",
    "Self-Storage REITs": "셀프스토리지 리츠",
    "Semiconductor Materials & Equipment": "반도체 소재 및 장비",
    "Semiconductors": "반도체",
    "Soft Drinks & Non-alcoholic Beverages": "청량·비알콜 음료",
    "Specialty Chemicals": "특수화학",
    "Specialized Consumer Services": "특화 소비자서비스",
    "Steel": "철강",
    "Systems Software": "시스템 소프트웨어",
    "Technology Distributors": "IT 유통",
    "Technology Hardware, Storage & Peripherals": "기술 하드웨어·저장장치·주변기기",
    "Telecom Tower REITs": "통신타워 리츠",
    "Timber REITs": "임업 리츠",
    "Tobacco": "담배",
    "Trading Companies & Distributors": "상사 및 유통",
    "Transaction & Payment Processing Services": "결제·거래처리 서비스",
    "Water Utilities": "수도 유틸리티",
    "Wireless Telecommunication Services": "무선통신 서비스",
    "Diversified REITs": "복합 리츠",
    "Office REITs": "오피스 리츠",
    "Industrial REITs": "산업용 부동산 리츠",
    "Health Care REITs": "헬스케어 리츠",
    "Specialized REITs": "특수목적 리츠",
    "Real Estate Services": "부동산 서비스",
    "Real Estate Operating Companies": "부동산 운영회사",
    "Diversified Metals & Mining": "복합 금속·광업",
    "Silver": "은",
    "Oil & Gas Drilling": "석유·가스 시추",
    "Oil & Gas Equipment & Services": "석유·가스 장비 및 서비스",
    "Oil & Gas Exploration & Production": "석유·가스 탐사 및 생산",
    "Oil & Gas Refining & Marketing": "석유·가스 정제 및 판매",
    "Oil & Gas Storage & Transportation": "석유·가스 저장 및 운송",
    "Coal & Consumable Fuels": "석탄 및 소비연료",
    "Airport Services": "공항 서비스",
    "Highways & Railtracks": "고속도로 및 철도 인프라",
    "Marine Transportation": "해상운송",
    "Marine Ports & Services": "항만 및 관련 서비스",
    "Diversified Chemicals": "복합 화학",
    "Commodity Chemicals": "범용 화학",
    "Packaged Foods & Meats": "가공식품 및 육류",
    "Agricultural & Farm Machinery": "농기계",
    "Diversified Capital Markets": "복합 자본시장",
    "Health Care REITs ": "헬스케어 리츠",
    "Semiconductor Equipment": "반도체 장비",
}


def translate(value):
    if not value:
        return value
    return SECTOR_KO.get(value) or SUB_INDUSTRY_KO.get(value) or value
